# Generated by Django 5.2.8 on 2025-11-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplicationarchive_jobapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
